export enum AcquiredStates {
  NOT_ACQUIRED = 'NOT_ACQUIRED',
  READY_TO_ACQUIRE = 'READY_TO_ACQUIRE',
  ACQUIRING = 'ACQUIRING',
  ACQUIRED = 'ACQUIRED',
  NOT_ACQUIRED_BC_ERROR = 'NOT_ACQUIRED_BC_ERROR'
}
